"""students table

Revision ID: 250bbec87fff
Revises: c58658553359
Create Date: 2025-09-05 10:48:19.749180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250bbec87fff'
down_revision = 'c58658553359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_forename'))
        batch_op.drop_index(batch_op.f('ix_student_surname'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_surname'), ['surname'], unique=1)
        batch_op.create_index(batch_op.f('ix_student_forename'), ['forename'], unique=1)

    # ### end Alembic commands ###
