"""teachers table

Revision ID: b330e1f97da5
Revises: 250bbec87fff
Create Date: 2025-09-05 11:37:32.501489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b330e1f97da5'
down_revision = '250bbec87fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forename', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('year_group', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_username'), ['username'], unique=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_student_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_student_teacher_id'))
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_username'))
        batch_op.drop_index(batch_op.f('ix_teacher_email'))

    op.drop_table('teacher')
    # ### end Alembic commands ###
