"""students table

Revision ID: c58658553359
Revises: 
Create Date: 2025-09-05 10:34:54.599865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58658553359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forename', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_forename'), ['forename'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_surname'), ['surname'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_username'))
        batch_op.drop_index(batch_op.f('ix_student_surname'))
        batch_op.drop_index(batch_op.f('ix_student_forename'))
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    # ### end Alembic commands ###
